## DEV overrides only

# Datasource URL
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/windsurf?currentSchema=hr-maternity-cn-dev
spring.datasource.url=jdbc:postgresql://122.152.220.47:9020/windsurf?currentSchema=hr-maternity-cn-dev

# JPA debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging (more verbose in dev)
logging.level.com.easy.care=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# encryption
encryption.secret-key=MySecretKey12345
# ?????? RSA??????????????
encryption.algorithm=RSA

encryption.rsa-public-key-pem=-----BEGIN PUBLIC KEY-----\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtx2qZ8G2mXv0LxF9yJ3L\
5bY0kC2lvb5x0o3WzYvPpX1xCw0GZp6zX0oKZ6k6YV2p7xQ9cTqZJ1vPZP7hJcL4\
s8J7gq1g4Gq3uVQj9lXeX0cS9p2b3w+7pL2oY1wK1t2wM2t8hK2Nf5xV7uZQvJ8B\
pi7jB8V7M3J5O1cLxR5xwUu9cN1a4kF9qP4iQ2R7mC3nV9tL2qK0xM5J7H0f1bOq\
J3tM8uQ2L5sV7iK2qL8cH2pT7nD3wN1pV5qU8eK2qZ4sM1vP9wE6nB2uM0qU9rL7\
bV3xF7uH2pQ9tL1oM3cJ5nR8sT0vL2xN1oK0wIDAQAB\
-----END PUBLIC KEY-----

encryption.rsa-private-key-pem=-----BEGIN PRIVATE KEY-----\
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3HapnwbaZe/Qv\
EX3IncvltjSQLaW9vnHSjdZNi8+lfXELDQZmnrNfSgpnqTphXanvFD1xOpgmW89k\
/uElwvizmnuCrWDgaru5VCN2Vd5fRxL2nZvfD7ukvahjXArW3bAzayBSsjX+cVe7\
mULyfAWmLuMHxXszcno7VwvFnnFBS71w3VrjQX2o/iJDJnubLedX20vaorTEzkns\
fR/Vs6ond0zy5DYvmxXuIrqovxwfahPucPfA3WlXmpTx4rapnizDW8/3ATqcHa4z\
SpT2svttXfEXu4falD20vWgzcnmcvLE9Ly9sTaCgtMCAwEAAQKCAQEAuZ3ZgVw9Z\
fVvC9hkb2Yw9VzC6d1bWGL7cS2m5e6tq0wVdQmVwPpK1R5t2YI0lH3c3p8G+uW3S\
2lCqD7uTr5ZxB1VgN1y3pHk1rV9WqYq7vKq4Vb+NqZP4xH9fV0ZyY7Dqv4K1jD5v\
hK3YF1fM0sW2VqG5rJ9wZz8Y2F9s1hT0eL7z2nZgN5i2FqT5sY0xLr3KkP9xHnL7\
c5qVnYf3dG2wV1pL3qV1uG3zK7rR8wY1lF2pN3mH8uNwL2pV7qZ9uK5xMvN0sF8q\
N2uV0sQ5vG2sR1pK0tYvL3J5mF2vQ3sY5L3hV1pT5wKBgQD5t8+9aZxf3Nqz5V9u\
bKq2xF8nT1vZ3rT6yG1cY5qF2sT4vL3xG1fP7qP1vC8w==\
-----END PRIVATE KEY-----

# email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.from=your-email@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
