## DEV overrides only

# Datasource URL
spring.datasource.url=jdbc:postgresql://122.152.220.47:9020/windsurf?currentSchema=hr-maternity-cn-dev

# JPA debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging (more verbose in dev)
logging.level.com.hr.maternity=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# encryption
encryption.secret-key=MySecretKey12345
encryption.algorithm=AES
